#
# Docker compose to kickstart a development environment
# based on docker.
#
# Start the environment
#
#   $ docker-compose up -d dev
#   $ docker attach -ti dati-semantic-lodview_dev_1
#
version: '3.9'
services:
  dev:
    image: openjdk:11-jdk-slim
    volumes:
      - .:/code:z
    working_dir: /code
    environment:
      - LodViewendpoint=https://schema.gov.it/sparql
    entrypoint:
    - /usr/bin/tail
    - -f
    - /dev/null
  lodview:
    build: .
    environment:
      - LodViewendpoint=https://schema.gov.it/sparql
      # - LodViewendpoint=http://sparql:8890/sparql
      # - LodViewIRInamespace=http://www.w3.org/
      # - LodViewhttpRedirectSuffix=
    volumes:
      - .:/code:z
    command: [
      "java",
      "-Djavax.net.ssl.trustStore=/code/test/truststore.jks",
      "-Djavax.net.ssl.trustStorePassword=changeit",
      "-jar",
      "/lodview.jar"]

